# See https://wiki.hypr.land/Configuring/Keywords/

$mod = SUPER
$amod = $mod ALT
$smod = $mod SHIFT
$cmod = $mod CONTROL
$csmod = $cmod SHIFT

# default applications
$terminal = ghostty
$explorer = nautilus --new-window
$browser = chromium
$launch_tui = $terminal -e

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mod, RETURN, exec, $terminal
bind = $mod, E, exec, $explorer
bind = $mod, B, exec, $browser

bind = $mod, T, exec, echo -e "Item 1\nItem 2\nItem 3" | walker --dmenu -n -t icon-launcher --height 1
bind = $smod, N, exec, launch-webapp "https://notion.so"
bind = $smod, C, exec, launch-webapp "https://claude.ai"
bind = $smod, M, exec, launch-webapp "https://music.youtube.com"
bind = $smod, W, exec, launch-webapp "https://web.whatsapp.com"

bind = $mod, W, killactive
bind = $mod, F, fullscreen, 1
bind = $smod, F, fullscreen, 0

bind = , PRINT, exec, grim ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
bind = SHIFT, PRINT, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
bind = CTRL, PRINT, exec, grim -g "$(slurp)" - | wl-copy

$noctalia = qs -c noctalia-shell ipc call

bind = $mod, SPACE, exec, $noctalia launcher toggle
bind = $mod, COMMA, exec, $noctalia settings toggle
bind = $smod, COMMA, exec, $launch_tui nvim ~/.config/hypr/hyprland.conf
bind = $smod, L, exec, $noctalia sessionMenu toggle

# Move focus with mod + arrow keys
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

# Switch workspaces with mod + [0-9]
# bind = $mod, TAB, switchworkspace
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# Move active window to a workspace with mod + SHIFT + [0-9]
bind = $smod, 1, movetoworkspace, 1
bind = $smod, 2, movetoworkspace, 2
bind = $smod, 3, movetoworkspace, 3
bind = $smod, 4, movetoworkspace, 4
bind = $smod, 5, movetoworkspace, 5
bind = $smod, 6, movetoworkspace, 6
bind = $smod, 7, movetoworkspace, 7
bind = $smod, 8, movetoworkspace, 8
bind = $smod, 9, movetoworkspace, 9
bind = $smod, 0, movetoworkspace, 10

# Move/resize windows with mod + LMB/RMB and dragging
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

